require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  CacheRootDirectory: ./tmp/cache

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

RSpec/NestedGroups:
  Max: 5

Style/NumberedParametersLimit:
  Enabled: false
